Repository Joshua-Pow/Placement, pull requests merged in 2024-03, with the labels that each got.

#68 issue66/form validation
  api/index.py
  api/polygon.py
  package-lock.json
  package.json
  public/adjust.png
  public/save.png
  public/upload.png
  src/components/FileUpload.tsx
  src/components/LoadingSkeleton.tsx
  src/components/Preview.tsx
  src/components/UploadForm.tsx
  src/components/ui/form.tsx
Labels: frontend

#64 Grace slice nesting 1
  api/index.py
  api/polygon.py
  api/slice_nesting.py
Labels: backend

#71 Issue70/show iterations
  api/index.py
  api/polygon.py
  api/resolution.py
  api/slice_nesting.py
  package-lock.json
  src/components/FileUpload.tsx
  src/components/IterationVisualizer.tsx
Labels: frontend, backend

#75 Issue74/Fixed the way duplicate pieces have their IDs generated
  api/index.py
  api/parse_svg_input_constaints.py
  api/polygon.py
Labels: backend
